services:
  mongoDB:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  app:
    container_name: app
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DB_HOST: mongodb
      DB_PORT: 27017
    ports:
      - 3000:3000
    depends_on:
      - mongoDB
